data = bytearray(100)
pointer = 0

data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
while data[pointer] != 0:
    pointer += 1
    data[pointer] += 1
    data[pointer] += 1
    data[pointer] += 1
    data[pointer] += 1
    data[pointer] += 1
    data[pointer] += 1
    data[pointer] += 1
    data[pointer] += 1
    pointer -= 1
    data[pointer] -= 1
pointer += 1
print(chr(data[pointer]), end='')
data[pointer] += 1
print(chr(data[pointer]), end='')
data[pointer] += 1
print(chr(data[pointer]), end='')
data[pointer] += 1
print(chr(data[pointer]), end='')
data[pointer] += 1
print(chr(data[pointer]), end='')
data[pointer] += 1
print(chr(data[pointer]), end='')
data[pointer] += 1
print(chr(data[pointer]), end='')
pointer -= 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
data[pointer] += 1
print(chr(data[pointer]), end='')
