data = bytearray(100)
p = 0

data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
while data[p] != 0:
    p += 1
    data[p] += 1
    data[p] += 1
    data[p] += 1
    data[p] += 1
    data[p] += 1
    data[p] += 1
    data[p] += 1
    data[p] += 1
    p -= 1
    data[p] -= 1
p += 1
print(chr(data[p]), end='')
data[p] += 1
print(chr(data[p]), end='')
data[p] += 1
print(chr(data[p]), end='')
data[p] += 1
print(chr(data[p]), end='')
data[p] += 1
print(chr(data[p]), end='')
data[p] += 1
print(chr(data[p]), end='')
data[p] += 1
print(chr(data[p]), end='')
p -= 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
data[p] += 1
print(chr(data[p]), end='')
